package org.phylospec.xml;

/**
 * Adds PhyloSpec provenance information to XML produced by backend integrations.
 */
public final class XmlProvenance {

    private XmlProvenance() {}

    /**
     * Embeds the PhyloSpec source as an XML comment immediately after the XML
     * declaration, or at the beginning of the document when no declaration exists.
     */
    public static String embedSource(String xml, String source) {
        String safeSource = makeXmlCommentSafe(source);
        boolean replacedDoubleHyphen = !safeSource.equals(source) && source.contains("--");

        StringBuilder comment = new StringBuilder();
        comment.append("\n<!--\n");
        comment.append("Generated by PhyloSpec.\n\n");
        comment.append("PhyloSpec source:\n");
        if (replacedDoubleHyphen) {
            comment.append(
                    "Note: XML comments cannot contain consecutive hyphens; "
                            + "they are displayed below with a space between them.\n");
        }
        comment.append(safeSource);
        if (!safeSource.endsWith("\n")) {
            comment.append('\n');
        }
        comment.append("-->\n");

        int declarationEnd = xml.startsWith("<?xml") ? xml.indexOf("?>") : -1;

        if (declarationEnd >= 0) {
            declarationEnd += 2;
            return xml.substring(0, declarationEnd) + comment + xml.substring(declarationEnd);
        }

        return comment.substring(1) + xml;
    }

    /**
     * XML comments cannot contain two consecutive hyphens. XML 1.0 also excludes
     * a small set of control characters, which are replaced to keep the output valid.
     */
    private static String makeXmlCommentSafe(String text) {
        StringBuilder safe = new StringBuilder();

        text.codePoints()
                .forEach(
                        codePoint -> {
                            if (codePoint == 0x9
                                    || codePoint == 0xA
                                    || codePoint == 0xD
                                    || (codePoint >= 0x20 && codePoint <= 0xD7FF)
                                    || (codePoint >= 0xE000 && codePoint <= 0xFFFD)
                                    || (codePoint >= 0x10000 && codePoint <= 0x10FFFF)) {
                                safe.appendCodePoint(codePoint);
                            } else {
                                safe.append('\uFFFD');
                            }
                        });

        return safe.toString().replace("--", "- -");
    }
}
