package tiling.xml;

import dr.app.beauti.util.XMLWriter;
import dr.inferencexml.model.CompoundLikelihoodParser;
import dr.inferencexml.operators.SimpleOperatorScheduleParser;
import dr.util.Attribute;
import dr.xml.XMLParser;
import tiling.BeastXState;

import java.io.StringWriter;
import java.util.ArrayList;
import java.util.List;

public class XmlDocumentWriter {

    public String write(
            BeastXState state,
            XmlPlan plan
    ) {
        validatePlan(plan);

        StringWriter output =
                new StringWriter();

        XMLWriter writer =
                new XMLWriter(output);

        writer.writeText("<?xml version=\"1.0\" standalone=\"yes\"?>");
        writer.writeComment("Generated by PhyloSpec BEAST X integration");
        writer.writeOpenTag(
                "beast",
                new Attribute.Default<>("version", "10.5.0")
        );
        writer.writeText("");

        writeBeastLevelDefinitions(writer, plan);
        writeOperators(writer, plan);
        writeMCMC(writer, state, plan);

        writeSection(writer, plan, XmlPlan.Section.AFTER_MCMC);

        writer.writeCloseTag("beast");
        writer.flush();

        return output.toString();
    }

    private void validatePlan(XmlPlan plan) {
        if (plan.isEmpty()) {
            throw new IllegalArgumentException(
                    "Cannot generate BEAST X XML from an empty XML plan."
            );
        }

        if (
                !plan.has(XmlPlan.Section.MCMC_PRIOR)
                        && !plan.has(XmlPlan.Section.MCMC_LIKELIHOOD)
        ) {
            throw new IllegalArgumentException(
                    "BEAST X XML generation requires at least one MCMC prior or likelihood element."
            );
        }

        if (!plan.has(XmlPlan.Section.OPERATORS)) {
            throw new IllegalArgumentException(
                    "BEAST X XML generation requires an operator schedule in the OPERATORS section."
            );
        }
    }

    private void writeBeastLevelDefinitions(
            XMLWriter writer,
            XmlPlan plan
    ) {
        writeSection(writer, plan, XmlPlan.Section.BEFORE_TAXA);
        writeSection(writer, plan, XmlPlan.Section.PARAMETERS);
        writeSection(writer, plan, XmlPlan.Section.TAXA);
        writeSection(writer, plan, XmlPlan.Section.TAXON_SETS);
        writeSection(writer, plan, XmlPlan.Section.ALIGNMENTS);
        writeSection(writer, plan, XmlPlan.Section.PATTERN_LISTS);
        writeSection(writer, plan, XmlPlan.Section.TREE_PRIOR_MODELS);
        writeSection(writer, plan, XmlPlan.Section.STARTING_TREES);
        writeSection(writer, plan, XmlPlan.Section.TREE_MODELS);
        writeSection(writer, plan, XmlPlan.Section.STATISTICS);
        writeSection(writer, plan, XmlPlan.Section.TREE_PRIOR_LIKELIHOODS);
        writeSection(writer, plan, XmlPlan.Section.BRANCH_RATE_MODELS);
        writeSection(writer, plan, XmlPlan.Section.SUBSTITUTION_SITE_MODELS);
        writeSection(writer, plan, XmlPlan.Section.CLOCK_PARAMETERS);
        writeSection(writer, plan, XmlPlan.Section.TREE_LIKELIHOODS);
    }

    private void writeOperators(
            XMLWriter writer,
            XmlPlan plan
    ) {
        writer.writeComment("Define operators");
        writer.writeOpenTag(
                SimpleOperatorScheduleParser.OPERATOR_SCHEDULE,
                new Attribute.Default<>(XMLParser.ID, "operators")
        );

        writeSection(writer, plan, XmlPlan.Section.OPERATORS);

        writer.writeCloseTag(SimpleOperatorScheduleParser.OPERATOR_SCHEDULE);
        writer.writeText("");
    }

    private void writeMCMC(
            XMLWriter writer,
            BeastXState state,
            XmlPlan plan
    ) {
        writer.writeComment("Define MCMC");

        List<Attribute> attributes =
                new ArrayList<>();

        attributes.add(new Attribute.Default<>(XMLParser.ID, state.runName + "_mcmc"));
        attributes.add(new Attribute.Default<>("chainLength", state.chainLength));
        attributes.add(new Attribute.Default<>("autoOptimize", "true"));

        writer.writeOpenTag("mcmc", attributes);

        if (plan.has(XmlPlan.Section.MCMC_LIKELIHOOD)) {
            writer.writeOpenTag(
                    CompoundLikelihoodParser.JOINT,
                    new Attribute.Default<>(XMLParser.ID, "joint")
            );
        }

        writer.writeOpenTag(
                CompoundLikelihoodParser.PRIOR,
                new Attribute.Default<>(XMLParser.ID, "prior")
        );
        writeSection(writer, plan, XmlPlan.Section.MCMC_PRIOR);
        writer.writeCloseTag(CompoundLikelihoodParser.PRIOR);

        if (plan.has(XmlPlan.Section.MCMC_LIKELIHOOD)) {
            writer.writeOpenTag(
                    CompoundLikelihoodParser.LIKELIHOOD,
                    new Attribute.Default<>(XMLParser.ID, "likelihood")
            );
            writeSection(writer, plan, XmlPlan.Section.MCMC_LIKELIHOOD);
            writer.writeCloseTag(CompoundLikelihoodParser.LIKELIHOOD);
            writer.writeCloseTag(CompoundLikelihoodParser.JOINT);
        }

        writer.writeIDref(SimpleOperatorScheduleParser.OPERATOR_SCHEDULE, "operators");
        writeSection(writer, plan, XmlPlan.Section.MCMC_LOGGERS);

        writer.writeCloseTag("mcmc");
        writer.writeText("");
    }

    private void writeSection(
            XMLWriter writer,
            XmlPlan plan,
            XmlPlan.Section section
    ) {
        for (XmlElement element : plan.get(section)) {
            element.write(writer);
        }
    }
}