package org.phylospec.xml;

import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.StringReader;
import javax.xml.parsers.DocumentBuilderFactory;
import org.junit.jupiter.api.Test;
import org.xml.sax.InputSource;

public class XmlProvenanceTest {

    @Test
    public void embedsPhyloSpecSourceAfterXmlDeclaration() throws Exception {
        String source = "data = readNexus(\"example.nex\");\n" + "tree ~ yule(1.0);\n";
        String xml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" + "<beast version=\"2.8\"/>";

        String result = XmlProvenance.embedSource(xml, source);

        assertTrue(result.startsWith("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!--"), result);
        assertTrue(result.contains("Generated by PhyloSpec."), result);
        assertTrue(result.contains(source), result);

        assertValidXml(result);
    }

    @Test
    public void keepsXmlValidWhenSourceContainsDoubleHyphen() throws Exception {
        String source = "// left--right\n";
        String xml = "<beast version=\"2.8\"/>";

        String result = XmlProvenance.embedSource(xml, source);

        assertTrue(result.contains("// left- -right"), result);
        assertTrue(result.contains("XML comments cannot contain consecutive hyphens"), result);

        assertValidXml(result);
    }

    private static void assertValidXml(String xml) throws Exception {
        DocumentBuilderFactory.newInstance()
                .newDocumentBuilder()
                .parse(new InputSource(new StringReader(xml)));
    }
}
