import org.junit.jupiter.api.Test;
import org.xml.sax.InputSource;

import javax.xml.parsers.DocumentBuilderFactory;
import java.io.StringReader;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.assertTrue;

public class BeastXXmlProvenanceTest {

    @Test
    public void embedsSourceInGeneratedBeastXXml() throws Exception {
        Path logPath =
                Path.of(
                        "target",
                        "beastx-xml-tests",
                        "phylospec-provenance.log"
                );
        String source =
                """
                PositiveReal x ~ LogNormal(
                    logMean=0.0,
                    logSd=1.0
                )

                mcmc {
                    Integer chainLength = 5
                    Integer randomSeed = 1234

                    Logger fileLogger = fileLogger(
                        logEvery=1,
                        file="%s",
                        parameters=[x]
                    )
                }
                """.formatted(logPath.toString().replace('\\', '/'));
        Path xmlPath =
                Path.of(
                        "target",
                        "beastx-xml-tests",
                        "phylospec-provenance.xml"
                );

        Files.deleteIfExists(xmlPath);

        new PhyloSpecRunner(source)
                .writeXml(
                        "phylospecProvenance",
                        xmlPath
                );

        String xml =
                Files.readString(xmlPath);

        assertTrue(xml.contains("Generated by PhyloSpec."), xml);
        assertTrue(xml.contains(source), xml);

        DocumentBuilderFactory.newInstance()
                .newDocumentBuilder()
                .parse(new InputSource(new StringReader(xml)));
    }
}
