package org.phylospec.components;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.annotation.processing.Generated;

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({"name", "namespace", "generatedType", "arguments"})
@Generated("jsonschema2pojo")
public class Generator__1 {

    /**
     *
     * (Required)
     *
     */
    @JsonProperty("name")
    private String name;

    /**
     * Namespace for this generator
     * (Required)
     *
     */
    @JsonProperty("namespace")
    @JsonPropertyDescription("Namespace for this generator")
    private String namespace;

    /**
     * Type generated by this generator
     *
     */
    @JsonProperty("generatedType")
    @JsonPropertyDescription("Type generated by this generator")
    private String generatedType;

    /**
     *
     * (Required)
     *
     */
    @JsonProperty("arguments")
    private List<Argument__1> arguments = new ArrayList<Argument__1>();

    @JsonIgnore
    private Map<String, Object> additionalProperties = new LinkedHashMap<String, Object>();

    /**
     *
     * (Required)
     *
     */
    @JsonProperty("name")
    public String getName() {
        return name;
    }

    /**
     *
     * (Required)
     *
     */
    @JsonProperty("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Namespace for this generator
     * (Required)
     *
     */
    @JsonProperty("namespace")
    public String getNamespace() {
        return namespace;
    }

    /**
     * Namespace for this generator
     * (Required)
     *
     */
    @JsonProperty("namespace")
    public void setNamespace(String namespace) {
        this.namespace = namespace;
    }

    /**
     * Type generated by this generator
     *
     */
    @JsonProperty("generatedType")
    public String getGeneratedType() {
        return generatedType;
    }

    /**
     * Type generated by this generator
     *
     */
    @JsonProperty("generatedType")
    public void setGeneratedType(String generatedType) {
        this.generatedType = generatedType;
    }

    /**
     *
     * (Required)
     *
     */
    @JsonProperty("arguments")
    public List<Argument__1> getArguments() {
        return arguments;
    }

    /**
     *
     * (Required)
     *
     */
    @JsonProperty("arguments")
    public void setArguments(List<Argument__1> arguments) {
        this.arguments = arguments;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(Generator__1.class.getName())
                .append('@')
                .append(Integer.toHexString(System.identityHashCode(this)))
                .append('[');
        sb.append("name");
        sb.append('=');
        sb.append(((this.name == null) ? "<null>" : this.name));
        sb.append(',');
        sb.append("namespace");
        sb.append('=');
        sb.append(((this.namespace == null) ? "<null>" : this.namespace));
        sb.append(',');
        sb.append("generatedType");
        sb.append('=');
        sb.append(((this.generatedType == null) ? "<null>" : this.generatedType));
        sb.append(',');
        sb.append("arguments");
        sb.append('=');
        sb.append(((this.arguments == null) ? "<null>" : this.arguments));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null) ? "<null>" : this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length() - 1)) == ',') {
            sb.setCharAt((sb.length() - 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result * 31) + ((this.name == null) ? 0 : this.name.hashCode()));
        result = ((result * 31) + ((this.namespace == null) ? 0 : this.namespace.hashCode()));
        result = ((result * 31) + ((this.arguments == null) ? 0 : this.arguments.hashCode()));
        result = ((result * 31) + ((this.additionalProperties == null) ? 0 : this.additionalProperties.hashCode()));
        result = ((result * 31) + ((this.generatedType == null) ? 0 : this.generatedType.hashCode()));
        return result;
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof Generator__1) == false) {
            return false;
        }
        Generator__1 rhs = ((Generator__1) other);
        return ((((((this.name == rhs.name) || ((this.name != null) && this.name.equals(rhs.name)))
                                        && ((this.namespace == rhs.namespace)
                                                || ((this.namespace != null) && this.namespace.equals(rhs.namespace))))
                                && ((this.arguments == rhs.arguments)
                                        || ((this.arguments != null) && this.arguments.equals(rhs.arguments))))
                        && ((this.additionalProperties == rhs.additionalProperties)
                                || ((this.additionalProperties != null)
                                        && this.additionalProperties.equals(rhs.additionalProperties))))
                && ((this.generatedType == rhs.generatedType)
                        || ((this.generatedType != null) && this.generatedType.equals(rhs.generatedType))));
    }
}
