package patternmatching;

import org.phylospec.ast.AstNode;
import org.phylospec.ast.Expr;
import org.phylospec.typeresolver.TypeResolver;

import java.lang.reflect.Field;
import java.lang.reflect.ParameterizedType;
import java.lang.reflect.Type;
import java.util.*;

public abstract class GeneratorTile<T> extends Tile {

    private final Type generatedType;

    protected GeneratorTile() {
        // parse the type parameter T
        Type superclass = this.getClass().getGenericSuperclass();
        if (superclass instanceof ParameterizedType pt) {
            this.generatedType = pt.getActualTypeArguments()[0];
        } else {
            throw new IllegalArgumentException("Generator tile " + this.getClass() + " has no type parameter. Set a type parameter to ensure type safety.");
        }
    }

    public abstract String getGeneratorName();

    @Override
    public Set<EvaluatedTile> tryToTile(AstNode node, Map<AstNode, Set<EvaluatedTile>> inputTiles, TypeResolver typeResolver) {
        if (!(node instanceof Expr.Call call)) return Set.of();
        if (!Objects.equals(call.functionName, this.getGeneratorName())) return Set.of();

        // the generator has the right name
        // we have to check if the passed arguments can be assigned using any of the objects generated by the input tiles

        // we first create a map of the argument tiles

        Map<String, Set<EvaluatedTile>> argumentTiles = new HashMap<>();
        for (Expr.Argument argument : call.arguments) {
            Set<EvaluatedTile> currentArgumentTiles = inputTiles.get(argument.expression);

            if (currentArgumentTiles == null) {
                throw new RuntimeException("Argument tiles not found. This should not happen.");
            }

            argumentTiles.put(argument.name, currentArgumentTiles);
        }

        // the expected inputs correspond to the class fields with type GeneratorTile.Input (similar to BEAST inputs)
        // we use reflection to get the expected inputs

        List<Input<?>> expectedInputs = new ArrayList<>();
        for (Field field : this.getClass().getDeclaredFields()) {
            if (field.getType().equals(Input.class)) {
                field.setAccessible(true);
                try {
                    Input<?> input = (Input<?>) field.get(this);
                    expectedInputs.add(input);
                } catch (IllegalAccessException e) {
                    throw new RuntimeException(e);
                }
            }
        }

        // we now go through all expected inputs and check if there is a tile with the right type

        int totalScore = this.getPriority().getScore();

        for (Input<?> expectedInput : expectedInputs) {
            Set<EvaluatedTile> possibleTiles = argumentTiles.get(expectedInput.getPhylospecArgumentName());

            if (possibleTiles == null || possibleTiles.isEmpty()) {
                // no input for this argument found. we cannot match this tile
                return Set.of();
            }

            int bestScore = 0;
            for (EvaluatedTile possibleTile : possibleTiles) {
                if (expectedInput.getTypeToken().isAssignableFrom(possibleTile.generatedType())) {
                    // we can use the input tile to assign it to this argument
                    bestScore = Math.max(bestScore, possibleTile.score());
                    expectedInput.setValue(possibleTile.generatedObject());
                }
            }

            if (bestScore == 0) {
                // none of the input tiles generate objects which can be assigned to the expected inputs
                // we cannot match this tile
                return Set.of();
            }

            totalScore += bestScore;
        }

        T generatedObject = this.operateTile();
        
        return Set.of(
                new EvaluatedTile(this, generatedObject, generatedType, totalScore)
        );
    }

    protected abstract T operateTile();

    public static class Input<T> {
        private final String phylospecArgumentName;
        private final TypeToken<T> typeToken;

        private T value;

        public Input(String phylospecArgumentName, TypeToken<T> typeToken) {
            this.phylospecArgumentName = phylospecArgumentName;
            this.typeToken = typeToken;
        }

        public String getPhylospecArgumentName() {
            return phylospecArgumentName;
        }

        public TypeToken<T> getTypeToken() {
            return typeToken;
        }

        public T getValue() {
            return value;
        }

        public void setValue(Object value) {
            this.value = (T) value;
        }
    }

}
