package patternmatching;

import org.phylospec.ast.AstNode;
import org.phylospec.ast.Expr;
import org.phylospec.typeresolver.TypeResolver;

import java.lang.reflect.Field;
import java.lang.reflect.Type;
import java.util.*;

public abstract class GeneratorTile<T> extends Tile {

    protected final Type generatedType;

    protected GeneratorTile() {
        this.generatedType = TileUtils.getParametricType(this);
        if (this.generatedType == null) {
            throw new IllegalArgumentException("Generator tile " + this.getClass() + " has no type parameter. Set a type parameter to ensure type safety.");
        }
    }

    public abstract String getGeneratorName();

    @Override
    public Set<EvaluatedTile> tryToTile(AstNode node, Map<AstNode, Set<EvaluatedTile>> inputTiles, TypeResolver typeResolver) {
        if (!(node instanceof Expr.Call call)) return Set.of();
        if (!Objects.equals(call.functionName, this.getGeneratorName())) return Set.of();

        // the generator has the right name
        // we have to check if the passed arguments can be assigned using any of the objects generated by the input tiles

        // we first create a map of the argument tiles

        Map<String, Set<EvaluatedTile>> argumentTiles = new HashMap<>();
        for (Expr.Argument argument : call.arguments) {
            Set<EvaluatedTile> currentArgumentTiles = inputTiles.get(argument.expression);

            if (currentArgumentTiles == null) {
                throw new RuntimeException("Argument tiles not found. This should not happen.");
            }

            argumentTiles.put(argument.name, currentArgumentTiles);
        }

        // the expected inputs correspond to the class fields with type GeneratorTile.Input (similar to BEAST inputs)
        // we use reflection to get the expected inputs

        List<Input<?>> expectedInputs = new ArrayList<>();
        for (Field field : this.getClass().getDeclaredFields()) {
            if (field.getType().equals(Input.class)) {
                field.setAccessible(true);
                try {
                    Input<?> input = (Input<?>) field.get(this);
                    expectedInputs.add(input);
                } catch (IllegalAccessException e) {
                    throw new RuntimeException(e);
                }
            }
        }

        // we now go through all expected inputs and check if there is a tile with the right type

        int totalScore = this.getPriority().getScore();

        for (Input<?> expectedInput : expectedInputs) {
            Set<EvaluatedTile> possibleTiles = argumentTiles.get(expectedInput.getPhylospecArgumentName());
            EvaluatedTile matchingTile = Tile.getBestInput(possibleTiles, expectedInput.getTypeToken());

            if (matchingTile == null) {
                // we cannot find a matching input
                // this tile cannot be matched
                return Set.of();
            }

            expectedInput.setValue(matchingTile.generatedObject());
            totalScore += matchingTile.score();
        }

        return this.operateTile(totalScore);
    }

    protected abstract Set<EvaluatedTile> operateTile(int score);

    public static class Input<T> {
        private final String phylospecArgumentName;
        private final TypeToken<T> typeToken;

        private T value;

        public Input(String phylospecArgumentName, TypeToken<T> typeToken) {
            this.phylospecArgumentName = phylospecArgumentName;
            this.typeToken = typeToken;
        }

        public String getPhylospecArgumentName() {
            return phylospecArgumentName;
        }

        public TypeToken<T> getTypeToken() {
            return typeToken;
        }

        public T getValue() {
            return value;
        }

        public void setValue(Object value) {
            this.value = (T) value;
        }
    }

}
